"""add api key scopes

Revision ID: 45bc597d978b
Revises: a3f8d2e14b92
Create Date: 2026-02-25 16:10:07.964568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45bc597d978b'
down_revision: Union[str, Sequence[str], None] = 'a3f8d2e14b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('scopes', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'memory_history', 'memories', ['memory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memory_history', type_='foreignkey')
    op.drop_column('api_keys', 'scopes')
    # ### end Alembic commands ###
