"""add api key scopes

Revision ID: 45bc597d978b
Revises: a3f8d2e14b92
Create Date: 2026-02-25 16:10:07.964568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45bc597d978b'
down_revision: Union[str, Sequence[str], None] = 'a3f8d2e14b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = set(inspector.get_table_names())

    if 'api_keys' in tables:
        api_key_columns = {col['name'] for col in inspector.get_columns('api_keys')}
        if 'scopes' not in api_key_columns:
            op.add_column('api_keys', sa.Column('scopes', sa.JSON(), nullable=True))

    if 'memory_history' in tables and 'memories' in tables:
        memory_history_columns = {col['name'] for col in inspector.get_columns('memory_history')}
        memories_columns = {col['name'] for col in inspector.get_columns('memories')}
        if 'memory_id' in memory_history_columns and 'id' in memories_columns:
            foreign_keys = inspector.get_foreign_keys('memory_history')
            fk_exists = any(
                fk.get('referred_table') == 'memories'
                and fk.get('constrained_columns') == ['memory_id']
                and fk.get('referred_columns') == ['id']
                for fk in foreign_keys
            )
            if not fk_exists:
                op.create_foreign_key(None, 'memory_history', 'memories', ['memory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = set(inspector.get_table_names())

    if 'memory_history' in tables:
        foreign_keys = inspector.get_foreign_keys('memory_history')
        for fk in foreign_keys:
            if (
                fk.get('referred_table') == 'memories'
                and fk.get('constrained_columns') == ['memory_id']
                and fk.get('referred_columns') == ['id']
                and fk.get('name')
            ):
                op.drop_constraint(fk['name'], 'memory_history', type_='foreignkey')
                break

    if 'api_keys' in tables:
        api_key_columns = {col['name'] for col in inspector.get_columns('api_keys')}
        if 'scopes' in api_key_columns:
            op.drop_column('api_keys', 'scopes')
    # ### end Alembic commands ###
