"""Add location to facts

Revision ID: 77d9b0593a71
Revises: 
Create Date: 2026-01-10 21:45:30.313178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d9b0593a71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facts', sa.Column('location', sa.String(), nullable=True))
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('users_drop_token_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_drop_token'), 'users', ['drop_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_drop_token'), table_name='users')
    op.create_unique_constraint(op.f('users_drop_token_key'), 'users', ['drop_token'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('facts', 'location')
    # ### end Alembic commands ###
