"""containerise_memory_layer

Revision ID: 8c11e99b811b
Revises: 2413e63f3794
Create Date: 2026-06-21 14:24:19.053711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c11e99b811b'
down_revision: Union[str, Sequence[str], None] = '2413e63f3794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_project_id'), 'chat_sessions', ['project_id'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'projects', ['project_id'], ['id'])
    op.add_column('documents', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'projects', ['project_id'], ['id'])
    op.add_column('entity_profiles', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_entity_profiles_project_id'), 'entity_profiles', ['project_id'], unique=False)
    op.create_foreign_key(None, 'entity_profiles', 'projects', ['project_id'], ['id'])
    op.add_column('facts', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_facts_project_id'), 'facts', ['project_id'], unique=False)
    op.create_foreign_key(None, 'facts', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'feedback_events', 'chunks', ['chunk_id'], ['id'])
    op.create_foreign_key(None, 'feedback_events', 'documents', ['document_id'], ['id'])
    op.add_column('memory_clusters', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_memory_clusters_project_id'), 'memory_clusters', ['project_id'], unique=False)
    op.create_foreign_key(None, 'memory_clusters', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'memory_history', 'memories', ['memory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memory_history', type_='foreignkey')
    op.drop_constraint(None, 'memory_clusters', type_='foreignkey')
    op.drop_index(op.f('ix_memory_clusters_project_id'), table_name='memory_clusters')
    op.drop_column('memory_clusters', 'project_id')
    op.drop_constraint(None, 'feedback_events', type_='foreignkey')
    op.drop_constraint(None, 'feedback_events', type_='foreignkey')
    op.drop_constraint(None, 'facts', type_='foreignkey')
    op.drop_index(op.f('ix_facts_project_id'), table_name='facts')
    op.drop_column('facts', 'project_id')
    op.drop_constraint(None, 'entity_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_entity_profiles_project_id'), table_name='entity_profiles')
    op.drop_column('entity_profiles', 'project_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_column('documents', 'project_id')
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_project_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'project_id')
    # ### end Alembic commands ###
